<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $perfumes = [
            [
                'name' => 'Sauvage Eau de Toilette',
                'description' => 'A fresh and spicy fragrance with a bold character. Perfect for the modern man who seeks adventure and freedom.',
                'price' => 95.00,
                'size' => '100ml',
                'type' => 'Eau de Toilette',
                'top_notes' => 'Calabrian Bergamot, Pepper',
                'heart_notes' => 'Sichuan Pepper, Lavender, Pink Pepper, Patchouli, Geranium, Elemi',
                'base_notes' => 'Labdanum, Ambroxan, Cedar, Vetiver',
                'category' => 'Fresh',
                'best_for' => 'All Season',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Bleu de Chanel',
                'description' => 'A timeless fragrance that embodies freedom. A woody aromatic fragrance with fresh citrus top notes.',
                'price' => 120.00,
                'size' => '100ml',
                'type' => 'Eau de Parfum',
                'top_notes' => 'Lemon, Mint, Pink Pepper, Grapefruit',
                'heart_notes' => 'Ginger, Nutmeg, Jasmine',
                'base_notes' => 'Incense, Cedar, Sandalwood, Patchouli, Labdanum, Vetiver',
                'category' => 'Fresh',
                'best_for' => 'All Season',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Acqua di Gio',
                'description' => 'A fresh aquatic fragrance inspired by the Mediterranean sea. Light and invigorating.',
                'price' => 85.00,
                'size' => '100ml',
                'type' => 'Eau de Toilette',
                'top_notes' => 'Marine Notes, Mandarin, Bergamot, Neroli',
                'heart_notes' => 'Jasmine, Rosemary, Calone, Persimmon',
                'base_notes' => 'Amber, Patchouli, White Musk',
                'category' => 'Fresh',
                'best_for' => 'Summer',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Tobacco Vanille',
                'description' => 'A warm and luxurious fragrance with rich tobacco and sweet vanilla. Perfect for evening wear.',
                'price' => 280.00,
                'size' => '100ml',
                'type' => 'Eau de Parfum',
                'top_notes' => 'Tobacco Leaf, Spicy Notes',
                'heart_notes' => 'Tonka Bean, Tobacco Flower, Vanilla',
                'base_notes' => 'Dried Fruits, Woody Notes',
                'category' => 'Oriental',
                'best_for' => 'Winter',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Santal 33',
                'description' => 'A unisex fragrance with a distinctive sandalwood character. Modern and sophisticated.',
                'price' => 260.00,
                'size' => '100ml',
                'type' => 'Eau de Parfum',
                'top_notes' => 'Violet, Cardamom, Ambrette',
                'heart_notes' => 'Iris, Papyrus, Ambrox',
                'base_notes' => 'Sandalwood, Cedar, Leather, Amber',
                'category' => 'Woody',
                'best_for' => 'Fall',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'La Vie Est Belle',
                'description' => 'A floral gourmand fragrance celebrating the joy of life. Sweet and feminine.',
                'price' => 110.00,
                'size' => '100ml',
                'type' => 'Eau de Parfum',
                'top_notes' => 'Blackcurrant, Pear',
                'heart_notes' => 'Iris, Jasmine, Orange Blossom',
                'base_notes' => 'Praline, Vanilla, Patchouli',
                'category' => 'Floral',
                'best_for' => 'All Season',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Black Opium',
                'description' => 'An addictive floral gourmand with coffee and vanilla. Bold and seductive.',
                'price' => 105.00,
                'size' => '90ml',
                'type' => 'Eau de Parfum',
                'top_notes' => 'Pink Pepper, Orange Blossom, Pear',
                'heart_notes' => 'Coffee, Jasmine, Bitter Almond',
                'base_notes' => 'Vanilla, Patchouli, Cedar',
                'category' => 'Oriental',
                'best_for' => 'Fall',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Aventus',
                'description' => 'A fruity chypre fragrance with pineapple and birch. Powerful and charismatic.',
                'price' => 325.00,
                'size' => '100ml',
                'type' => 'Eau de Parfum',
                'top_notes' => 'Pineapple, Apple, Bergamot, Blackcurrant',
                'heart_notes' => 'Birch, Patchouli, Jasmine, Rose',
                'base_notes' => 'Musk, Oakmoss, Ambergris, Vanilla',
                'category' => 'Woody',
                'best_for' => 'All Season',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Light Blue',
                'description' => 'A fresh and vibrant fragrance with Mediterranean notes. Crisp and energizing.',
                'price' => 75.00,
                'size' => '100ml',
                'type' => 'Eau de Toilette',
                'top_notes' => 'Sicilian Lemon, Apple, Cedar, Bellflower',
                'heart_notes' => 'Bamboo, Jasmine, White Rose',
                'base_notes' => 'Amber, Cedarwood, Musk',
                'category' => 'Fresh',
                'best_for' => 'Summer',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Oud Wood',
                'description' => 'A luxurious woody fragrance with oud and sandalwood. Rich and sophisticated.',
                'price' => 290.00,
                'size' => '100ml',
                'type' => 'Eau de Parfum',
                'top_notes' => 'Pink Pepper, Cardamom, Coriander',
                'heart_notes' => 'Oud, Rosewood, Sandalwood',
                'base_notes' => 'Tonka Bean, Vanilla, Amber',
                'category' => 'Woody',
                'best_for' => 'Winter',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Good Girl',
                'description' => 'A floral oriental fragrance with tuberose and tonka bean. Elegant and mysterious.',
                'price' => 98.00,
                'size' => '80ml',
                'type' => 'Eau de Parfum',
                'top_notes' => 'Almond, Coffee',
                'heart_notes' => 'Tuberose, Jasmine, Bulgarian Rose',
                'base_notes' => 'Tonka Bean, Cacao, Patchouli, Sandalwood',
                'category' => 'Oriental',
                'best_for' => 'Fall',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Eros',
                'description' => 'A fresh oriental fragrance with mint and vanilla. Energetic and passionate.',
                'price' => 88.00,
                'size' => '100ml',
                'type' => 'Eau de Toilette',
                'top_notes' => 'Mint, Green Apple, Lemon',
                'heart_notes' => 'Tonka Bean, Ambroxan, Geranium',
                'base_notes' => 'Vanilla, Vetiver, Oakmoss, Cedarwood',
                'category' => 'Fresh',
                'best_for' => 'All Season',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Flowerbomb',
                'description' => 'An explosive floral fragrance with jasmine and rose. Feminine and powerful.',
                'price' => 125.00,
                'size' => '100ml',
                'type' => 'Eau de Parfum',
                'top_notes' => 'Bergamot, Orange, Tea',
                'heart_notes' => 'Jasmine, Orchid, Rose, Freesia',
                'base_notes' => 'Patchouli, Musk',
                'category' => 'Floral',
                'best_for' => 'Spring',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Spicebomb',
                'description' => 'A spicy oriental fragrance with saffron and tobacco. Bold and intense.',
                'price' => 95.00,
                'size' => '90ml',
                'type' => 'Eau de Toilette',
                'top_notes' => 'Bergamot, Grapefruit, Pink Pepper, Elemi',
                'heart_notes' => 'Saffron, Cinnamon, Paprika',
                'base_notes' => 'Tobacco, Leather, Vetiver',
                'category' => 'Spicy',
                'best_for' => 'Winter',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Coco Mademoiselle',
                'description' => 'A modern and elegant fragrance with orange and patchouli. Sophisticated and timeless.',
                'price' => 115.00,
                'size' => '100ml',
                'type' => 'Eau de Parfum',
                'top_notes' => 'Orange, Mandarin, Orange Blossom',
                'heart_notes' => 'Rose, Jasmine, Mimosa',
                'base_notes' => 'Patchouli, Vetiver, Vanilla, White Musk',
                'category' => 'Floral',
                'best_for' => 'All Season',
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        foreach ($perfumes as $perfume) {
            Product::create($perfume);
        }
    }
}

